version: '3'
services:
  helloworld:
    image: freshboyeee/helloworld
  mynginx:
    image: freshboyeee/mynginx:2.0
    ports:
    - "5001:80"
  mycat:
    image: freshboyeee/cat:2.0
    ports:
    - "5000:5000"
